name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_read_more_text: ^0.0.6
  card_swiper: ^3.0.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.1.2
  path_provider: ^2.1.4
  read_more_text: ^0.0.5

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/images/

  fonts:
    - family: Cinematic
      fonts:
        - asset: assets/fonts/Cinematic.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_native_splash:
  color: "#ffffff"